[package]
name = "ai-world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.19"
egui-macroquad = "0.12"
macroquad = "0.3"
rand = "0.8.5"

