[package]
name = "ai-world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21"
egui_extras = "0.21"
rand = "0.8.5"
rand_distr = "0.4.3"
tracing-subscriber = "0.3.16"

